apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sample-blog
  namespace: openshift-gitops
spec:
  destinations:
  - namespace: sample-blog
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/skitamura7446/rosa-sample-blog.git 
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

